### PR TITLE
Fix preprocessing. Now works without npz

### PR DESCRIPTION
**Pull request by pyg4thr1x**

### CODE REVIEW

**Comment by hcw1026** [comment]
Line 296 -- help argument, what does it mean
Line 300-- What does it mean

**Comment by hcw1026** [comment]
Have made some changes. Have a look at the changes to see if you agree. I have not tested my changes tho… Other than this, I'm happy with the PR

**Comment by pyg4thr1x** [comment]
Ok, line 296 means set start and stop, what we do when we use tmux.
line 300 means that to do that you need to have a random seed

**Comment by pyg4thr1x** [comment]
You need int in --split, otherwise line 328 won't work

**Review by hcw1026 — APPROVED** [review]

**Pull request merged**
