### PR TITLE
aden davide datawrangle

### PR DESCRIPTION
**Pull request by hcw1026**
I have checked that all the functions apart from the set_path now works. I have not checked all the set_path functions yet. 

I have run through the scripts and produced four different csv files on Boden:
/srv/data/urop/track_fetch.csv                                       
----The csv from track_fetch.py

/srv/data/urop/track_wrangle_with_dup.csv                  
----The csv from track_wrangle.py with duplicates generated by track_fetch.csv

/srv/data/urop/track_wrangle_without_dup.csv             
----The csv from track_wrangle.py without duplicates generated by track_fetch.csv

/srv/data/urop/track_wrangle_silence_with_dup.csv      
----The csv from track_wrangle_silence.py generated by track_wrangle_with_dup.csv

Things that NEED to be tested further:
1. All the set_path functions and global issues
2. The final __name__=='__main__' -- I have not checked this yet.

### CODE REVIEW

**Comment by pyg4thr1x** [comment]
Check out my "Add fancy comment" commit. CSV files are now generating with a # comment at the beginning with the command used to generate it. This is one of my fancy "last minutes changes" 😇

Feel free to revert it if you don't like it. Other than that, assuming that someone tested the wrangle and wrangle_silence scripts on Boden, we are good to go for me 👍

**Comment by pyg4thr1x** [comment]
@hcw1026 The set_path functions are not really used if the py files are runned as script (those are useful when you import the files, which we won't, but Calle and I thought there's no harm in keeping those functions)

**Comment by pyg4thr1x** [comment]
I have checked all the scripts (running everything from terminal, no importing), and EVERYTHING WORKS. The output produced are consistent with Aden's, they are in now in /srv/data/urop/ (I've moved all previous Aden's files in the "aden" folder)

**Comment by pyg4thr1x** [comment]
I've added/changed/improved a couple of things: 1) changed dtype of channels column from float to int; 2) added a line of comment in the output file that shows which parameters were used to create it (very useful in my opinion); 3) added a couple of sanity checks to make sure that the input file is the correct one and 4) produced an ultimate.csv (with the parameters that you'll see in the first line of comment in the file) which should contain all the really good tracks (feel free to tweak the parameters and update the file)

**Comment by pyg4thr1x** [comment]
Now, I think that the 4 scripts in the scripts folder + the 6 csv files currently in /srv/data/urop capture ALL the information we might possibly need in the future from summary file/mp3 files. I am rather satisfied of those scripts, and I don't think there's much else to be added. Some parts of the code might be a bit obscure, but the scripts themselves should be extremely easy to use

**Review by callesonne — COMMENTED** [review]
I will post reviews of each script separately.

Review for track_fetch.py:
---------------------------------
- Why do we have the option to store relative paths if every function then has to start with os.path.join(mp3_root_dir, path)? If there is a reason for this I'm all for it but it just feels like it adds unnecessary amounts of code.
- In check_mutagen_info, the 2nd except block I do not see the reason for. If this block catches an error then it will print a warning but then continue through the loop and as you store lengths and channels in lists this will cause them to "lag behind" the paths by one index per exception. Unless I'm missing something it feels like this exception should either add a blank line as the above, or quit the script i.e. remove the exception block.
- In check_mutagen_info, shouldn't `start = time.time()` be in the for loop? From reading the verbose print line it seems that the time should be referring to time it took to process one id, not all of the ids since the start.
- In check_mutagen_info, I dont understand the `if debug:` part. Why do you only print the lengths? Why not also the channels? (Also @pyg4thr1x this is a good place for inline documentation!)
- Another question: why is `df['channels'] = df['channels'].apply(lambda x: int(x))` necessary? Are there sometimes non-integer amount of channels showing?
- It seems that you prefer `if ... == True`and `if ... == False` as opposed to `if ...` and `if not ...`. In my opinion I always prefered the latter because its shorter, do you have a specific reason for using the prior?
- I also think the optional arguments "--skip-os" and "--skip-mutagen" should be explained better. In my opinion the prior ones you used, "--no-length", "--no-channels" and "--no-size" were much more intuitive. Does "--skip-os" mean avoid using the os module? It says in the comment "do not calculate tracks size" but why not name is "--skip-size" then?? Also what option skips channels? It seems by the comment on "--skip-mutagen" that it only skips track length, so you have less options than before?

I will also soon commit some minor documentation changes, like adding docstrings to each function

**Review by callesonne — COMMENTED** [review]
Review for track_wrangle.py:
-------------------------------------
extract_ids_from_summary:
- Why do you replace NA with zeros in `df_summary['year']`? Also, why do we store year? I dont see it used anywhere

df_purge_duplicates:
- I dont understand this code (@pyg4thr1x another good place for inline comments!). To me it seems that you loop through each "sublist" then if its bigger than one remove ONE tid from sublist and then continue with the next sublist? Are all sublist max length 2? Or am I missing something? It feels as if it should be `while len(sublist) > 1:` instead of `if len(sublist) > 1`

Once again I will soon push some documentation changes. Please, even though some functions are small, have a docstring in all functions and then add a blank line before code. Docstring can be a one liner if there is no ambiguity about return type/parameters.

**Review by callesonne — COMMENTED** [review]
Review of mp3_to_npz.py
----------------------------------

Functions:

no_sound:
- the line `path_npz = os.path.join(npz_root_dir, path[:-9] + '.npz')`, doesn't this assume that the paths stored are already relative? I am pretty sure track_fetch.py gives you the option to choose (one of my comments on that script was that I would prefer to only store absolute paths, so if we decide to implement that then this will have to change).
- You seem to only print time if verbose == true, but you still seem to run time.time regardless. In my opinion we should add to the beggining: `if verbose: start = time.time()`

no_sound_count:
- As above I think you assume that file_path is relative, I could be wrong though.
- I dont think final_check should be explained better. Does it returns paths who have not been loaded and saved correctly? This is not evident from the description "If True, peform a final check", without explaining what "a final check" is.

General:

I think the descriptions of functions in the script docstring should be a minimal summary of the function to get an idea of what it does. For an actual descritption they should read the function docstring. Therefore I shortened some of them, e.g. no_sound_count where parameters were explained in the script docstring. Remember also to have an initial line in each docstring to summarize the function without going into detail, this line will then be displayed by pydoc.

**Comment by callesonne** [comment]
Just wanted to add that I, of course, have gone through all functions. If I dont comment on one then I am happy with it.

**Review by callesonne — COMMENTED** [review]
This one is not done, but I do not know how to save reviews so here is a preview (hopefully finished today):

Review of track_wrangle_silence:
-------------------------------------------
Functions:

check_silence:
- Please document this, it is a 50+ line function with no in-line documentation which makes it hard to read.

General:
The first line (summary) in each function docstring seems to be missing, I can probably fix this. https://numpydoc.readthedocs.io/en/latest/format.html

**Comment by hcw1026** [comment]
> This one is not done, but I do not know how to save reviews so here is a preview (hopefully finished today):
> 
> ## Review of track_wrangle_silence:
> Functions:
> 
> check_silence:
> 
> * Please document this, it is a 50+ line function with no in-line documentation which makes it hard to read.
> 
> General:
> The first line (summary) in each function docstring seems to be missing, I can probably fix this. https://numpydoc.readthedocs.io/en/latest/format.html

Inline doc sorted

**Comment by hcw1026** [comment]
> ## Review for track_wrangle.py:
> extract_ids_from_summary:
> 
> * Why do you replace NA with zeros in `df_summary['year']`? Also, why do we store year? I dont see it used anywhere
> 
> df_purge_duplicates:
> 
> * I dont understand this code (@pyg4thr1x another good place for inline comments!). To me it seems that you loop through each "sublist" then if its bigger than one remove ONE tid from sublist and then continue with the next sublist? Are all sublist max length 2? Or am I missing something? It feels as if it should be `while len(sublist) > 1:` instead of `if len(sublist) > 1`
> 
> Once again I will soon push some documentation changes. Please, even though some functions are small, have a docstring in all functions and then add a blank line before code. Docstring can be a one liner if there is no ambiguity about return type/parameters.

@pyg4thr1x year has no NA values so we can delete this line I think, there are already represented by zero according to the analysis

**Comment by hcw1026** [comment]
> ## Review of mp3_to_npz.py
> Functions:
> 
> no_sound:
> 
> * the line `path_npz = os.path.join(npz_root_dir, path[:-9] + '.npz')`, doesn't this assume that the paths stored are already relative? I am pretty sure track_fetch.py gives you the option to choose (one of my comments on that script was that I would prefer to only store absolute paths, so if we decide to implement that then this will have to change).
> * You seem to only print time if verbose == true, but you still seem to run time.time regardless. In my opinion we should add to the beggining: `if verbose: start = time.time()`
> 
> no_sound_count:
> 
> * As above I think you assume that file_path is relative, I could be wrong though.
> * I dont think final_check should be explained better. Does it returns paths who have not been loaded and saved correctly? This is not evident from the description "If True, peform a final check", without explaining what "a final check" is.
> 
> General:
> 
> I think the descriptions of functions in the script docstring should be a minimal summary of the function to get an idea of what it does. For an actual descritption they should read the function docstring. Therefore I shortened some of them, e.g. no_sound_count where parameters were explained in the script docstring. Remember also to have an initial line in each docstring to summarize the function without going into detail, this line will then be displayed by pydoc.

explained final_check

**Comment by pyg4thr1x** [comment]
> I will post reviews of each script separately.
> 
> ## Review for track_fetch.py:
> * Why do we have the option to store relative paths if every function then has to start with os.path.join(mp3_root_dir, path)? If there is a reason for this I'm all for it but it just feels like it adds unnecessary amounts of code.
> * In check_mutagen_info, the 2nd except block I do not see the reason for. If this block catches an error then it will print a warning but then continue through the loop and as you store lengths and channels in lists this will cause them to "lag behind" the paths by one index per exception. Unless I'm missing something it feels like this exception should either add a blank line as the above, or quit the script i.e. remove the exception block.
> * In check_mutagen_info, shouldn't `start = time.time()` be in the for loop? From reading the verbose print line it seems that the time should be referring to time it took to process one id, not all of the ids since the start.
> * In check_mutagen_info, I dont understand the `if debug:` part. Why do you only print the lengths? Why not also the channels? (Also @pyg4thr1x this is a good place for inline documentation!)
> * Another question: why is `df['channels'] = df['channels'].apply(lambda x: int(x))` necessary? Are there sometimes non-integer amount of channels showing?
> * It seems that you prefer `if ... == True`and `if ... == False` as opposed to `if ...` and `if not ...`. In my opinion I always prefered the latter because its shorter, do you have a specific reason for using the prior?
> * I also think the optional arguments "--skip-os" and "--skip-mutagen" should be explained better. In my opinion the prior ones you used, "--no-length", "--no-channels" and "--no-size" were much more intuitive. Does "--skip-os" mean avoid using the os module? It says in the comment "do not calculate tracks size" but why not name is "--skip-size" then?? Also what option skips channels? It seems by the comment on "--skip-mutagen" that it only skips track length, so you have less options than before?
> 
> I will also soon commit some minor documentation changes, like adding docstrings to each function

1. Let’s remove the absolute path option then, and only store relative paths. I would add the MP3 root dir as a comment in the output file of track_fetch though;
2. You are right. Let’s remove the second exception
3. I actually wanted to see the time that has elapsed so far, but that doesn’t really matter... feel free to change that
4. Yes, you’re again right: that’s a good place for inline doc. Length and channel are the same thing for debugging purposes - when there’s an error in one, there’s also in the other one
5. Channels by default are float (stereo is shown as ‘2.0’)
6. I don’t really mind. My reasoning was that you don’t want to pass an int (or whatever else) instead of a bool in the function and have everything run smoothly. But maybe if ... and if not ... are simply better
7. I rewrote that function from scratch, because that’s where we were having all the issues, so in that very moment “—skip-mutagen” seemed more intuitive to me. I’m happy to have it changed back

**Comment by pyg4thr1x** [comment]
> > ## Review for track_wrangle.py:
> > extract_ids_from_summary:
> > 
> > * Why do you replace NA with zeros in `df_summary['year']`? Also, why do we store year? I dont see it used anywhere
> > 
> > df_purge_duplicates:
> > 
> > * I dont understand this code (@pyg4thr1x another good place for inline comments!). To me it seems that you loop through each "sublist" then if its bigger than one remove ONE tid from sublist and then continue with the next sublist? Are all sublist max length 2? Or am I missing something? It feels as if it should be `while len(sublist) > 1:` instead of `if len(sublist) > 1`
> > 
> > Once again I will soon push some documentation changes. Please, even though some functions are small, have a docstring in all functions and then add a blank line before code. Docstring can be a one liner if there is no ambiguity about return type/parameters.
> 
> @pyg4thr1x year has no NA values so we can delete this line I think, there are already represented by zero according to the analysis

@callesonne, I think it is good to store year, and also to have it in the TFRecords, as it can be useful information. @hcw1026 there are actually NaN's in the summary file, since pandas considers NaN as a float, I replace NaN's with 0's and then convert the column to int.

@callesonne, as for the duplicates, I am removing one element from the list of idx's to drop, so the correct syntax is if, not while. I'll comment that

**Comment by pyg4thr1x** [comment]
> ## Review of mp3_to_npz.py
> Functions:
> 
> no_sound:
> 
> * the line `path_npz = os.path.join(npz_root_dir, path[:-9] + '.npz')`, doesn't this assume that the paths stored are already relative? I am pretty sure track_fetch.py gives you the option to choose (one of my comments on that script was that I would prefer to only store absolute paths, so if we decide to implement that then this will have to change).
> * You seem to only print time if verbose == true, but you still seem to run time.time regardless. In my opinion we should add to the beggining: `if verbose: start = time.time()`
> 
> no_sound_count:
> 
> * As above I think you assume that file_path is relative, I could be wrong though.


@callesonne, os.path.join works both with absolute and relative paths. os.path.join('/usr/var/foo.py', 'var/foo.py') returns '/usr/var/foo.py'. Try it

**Comment by pyg4thr1x** [comment]
@callesonne, I went through all your comments. I either changed the code, or added a line of comments to explain why things are how they are. Feel free to change the code if you need more changes are necessary

**Comment by callesonne** [comment]
> > ## Review of mp3_to_npz.py
> > Functions:
> > no_sound:
> > 
> > * the line `path_npz = os.path.join(npz_root_dir, path[:-9] + '.npz')`, doesn't this assume that the paths stored are already relative? I am pretty sure track_fetch.py gives you the option to choose (one of my comments on that script was that I would prefer to only store absolute paths, so if we decide to implement that then this will have to change).
> > * You seem to only print time if verbose == true, but you still seem to run time.time regardless. In my opinion we should add to the beggining: `if verbose: start = time.time()`
> > 
> > no_sound_count:
> > 
> > * As above I think you assume that file_path is relative, I could be wrong though.
> 
> @callesonne, os.path.join works both with absolute and relative paths. os.path.join('/usr/var/foo.py', 'var/foo.py') returns '/usr/var/foo.py'. Try it

That is not the problem, if both paths are absolute you get this:
`>>> npz_root_dir = '/srv/data/urop/7digital_numpy/'`
`>>> mp3_path = '/srv/data/urop/7digital/1/2/12341234'`
`>>> os.path.join(npz_root_dir, mp3_path)`
`'/srv/data/urop/7digital/1/2/12341234'`
In other words, if mp3 path is absolute you wont get the npz path

**Comment by callesonne** [comment]
Although since it seems we removed the absolute path option, it seems we dont necessarily need to fix this.

**Comment by callesonne** [comment]
> 6. I don’t really mind. My reasoning was that you don’t want to pass an int (or whatever else) instead of a bool in the function and have everything run smoothly. But maybe if ... and if not ... are simply better

I did not know that. So while `1 == True`  returns True, `2 == True` is false. This was just a thought I had while reading the code, not something that needs to be fixed, fixing it would probably be a waste of time.

**Comment by pyg4thr1x** [comment]
> That is not the problem, if both paths are absolute you get this:
> `>>> npz_root_dir = '/srv/data/urop/7digital_numpy/'`
> `>>> mp3_path = '/srv/data/urop/7digital/1/2/12341234'`
> `>>> os.path.join(npz_root_dir, mp3_path)`
> `'/srv/data/urop/7digital/1/2/12341234'`
> In other words, if mp3 path is absolute you wont get the npz path

Now I see what you mean! There's my amazing `mp3_path_to_npz_path` for that, and we forgot to apply it there!

I just fixed that. The only extra thing I had to edit is the savez function: now it takes two inputs, the path of the mp3 and the path of the npz output. Before it was calculating the path of the npz output automatically, but this way we don't have to compute the same thing twice. @hcw1026, I know you did't like that, but it seemed more efficient to me in this context

**Review by callesonne — APPROVED** [review]
Im happy.

**Pull request merged**
