### PR TITLE
Aden calle model

### PR DESCRIPTION
**Pull request by callesonne**
This pull request contains the custom training loop as well as custom testing + prediction functions

### CODE REVIEW

**Comment by pyg4thr1x** [comment]
I've removed the beta script (it was exactly the same as the other one...), and I've moved the predict module to a different branch (maybe for predictions let's just use model.predict()?).

I assume the script has already been tested...

Looks good to me

**Review by pyg4thr1x — DISMISSED** [review]

**Comment by callesonne** [comment]
Im not sure bout using system-args for the training scripts. It seems you have already done this and put in a lot of work to do it, so we sould keep it, but in my opinion when we have these many arguments I feel its easier to just edit the file directly

**Comment by pyg4thr1x** [comment]
Done & tested.

**Comment by hcw1026** [comment]
I just need to add some docs and I'm trying to figure out the memory problem. And we also need to fix the printing issue. Other than that, this PR is ready

**Comment by callesonne** [comment]
Do we remove projecname_input2 now that the real RAM thief has been found? I found projectname_input2 very wierd, didnt really see the point of the functions withing the windowing functions... Does the tf.where line even work? random is a boolean and according to the documentation x and y needs to have the same shape, yet they are slices of audio.

**Comment by pyg4thr1x** [comment]
I took a look at the commits. If you guys tested it (and I think you have, since we're using this right now), this PR is good to go to me

**Review by pyg4thr1x — DISMISSED** [review]

**Comment by callesonne** [comment]
Do we need to use gc.collect() now that we know what the real reason we were having a memory leak was?

**Comment by pyg4thr1x** [comment]
> Do we need to use gc.collect() now that we know what the real reason we were having a memory leak was?

@hcw1026? What did gc.collect() even do?

**Review by pyg4thr1x — DISMISSED** [review]

**Comment by hcw1026** [comment]
gc.collect() just asks python to collect garbage. I will try to run scripts without gc.collect() after this waveform training (don't want to accidently kill Boden at the moment....)

**Comment by pyg4thr1x** [comment]
I'd merge it now. If you guys have any minor changes just submit a new PR

**Review by pyg4thr1x — APPROVED** [review]

**Pull request merged**
