### PR TITLE
Davide input little change

### PR DESCRIPTION
**Pull request by pyg4thr1x**
Changelog:
1) Add possibility to merge tags together (important feature we forgot about!!)
2) sample_rate is not a global variable anymore, num_tags inferred

### CODE REVIEW

**Comment by hcw1026** [comment]
For generate dataset split, I prefer the previous one with 'which' and 'train_val_test_split', since the original function allows us to choose the exact number (especially when we just want to train a smaller portion when we test our scripts) and location.

**Comment by hcw1026** [comment]
Other than generate_datasets_with_split(), I am happy with this PR

**Comment by pyg4thr1x** [comment]
I still think which() is a bit redundant... 

I removed the rescaling-split thingy, now in split you simply specify the number of files you want.

In this way I don't think which() is required...

**Comment by callesonne** [comment]
Im happy with everything other than generate_datasets_with_split() as well. Will push a commit in a minute with some minor changes to the code

**Comment by callesonne** [comment]
Also Im pretty sure we need to convert to dense instantly in the _parse_features function. To be honset I would prefer it if we merged reshape and _parse_features.

**Comment by pyg4thr1x** [comment]
Now I'm happy. Added split to generate_datasets (why not?). cycle_length was missing in .interleave (that was an actual bug). The rest is the same. Tested

**Comment by hcw1026** [comment]
I have made some minor changes, please look at it and if you agree, please merge

**Review by hcw1026 — APPROVED** [review]

**Pull request merged**
