### PR TITLE
Train with fit

### PR DESCRIPTION
**Pull request by pyg4thr1x**
Done & tested.

Run `python training.py waveform --split 80 10 10  --epochs 3`

### CODE REVIEW

**Comment by hcw1026** [comment]
Line 89: resume_time path seems wrong to me

**Comment by hcw1026** [comment]
Except that and my changes, it only needs some extra doc and I'm ready to accept

**Comment by hcw1026** [comment]
check out the new parser. I have not read any changes made after my last comment yet. I'll do it once I finish the input PR

**Comment by pyg4thr1x** [comment]
1. Fix early_stop = None in model.fit

**Comment by pyg4thr1x** [comment]
Fixed one bug (in Aden's new parser: .union is not inplace), and added the possibility to go without early stop. This is good to go to me

**Review by callesonne — COMMENTED** [review]
Review
----------

_required_length:
is this used anywhere? If so we should delete it right?

get_compiled_model:
Im not sure if model.load_weights will work when resuming from a script used for training_gradtape as that one saves a checkpoint containing both the model and the optimizer. We can test this when we actually need to do that.

train:
Continuing on the previous point, they are most definately not compatible.. this script uses model.save (in the checkpoint) whilst training_gradtape uses the checkpoint class.

Other than this, Im happy with it. We can probably fix so that we can resume regardless of what script was used, but that will need some more code.

**Comment by pyg4thr1x** [comment]
> _required_length:
> is this used anywhere? If so we should delete it right?

Deleted.

**Comment by pyg4thr1x** [comment]
> get_compiled_model:
> Im not sure if model.load_weights will work when resuming from a script used for training_gradtape as that one saves a checkpoint containing both the model and the optimizer. We can test this when we actually need to do that.

Don't know. Why are you saving model and optimizer? Aren't plain weights enough? Should test it though

**Comment by pyg4thr1x** [comment]
> get_compiled_model:
> Im not sure if model.load_weights will work when resuming from a script used for training_gradtape as that one saves a checkpoint containing both the model and the optimizer. We can test this when we actually need to do that.
> 
> train:
> Continuing on the previous point, they are most definately not compatible.. this script uses model.save (in the checkpoint) whilst training_gradtape uses the checkpoint class.

@callesonne, I look a bit into it, and the simple answer is: you can't load a model trained with model.fit into gradtape, and viceversa. The reason for it is that tf.train.Checkpoint.save (which is the preferred way to save checkpoints) is not compatible with tf.keras.Model.save_weights (which is the default keras callback), even if they save in the same format.

A possible workaround would be to write a custom callback which makes use of tf.train.Checkpoint.save. I think I'd leave that to another PR though...

Check this out for details: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/train/Checkpoint, at the end of the article

**Comment by pyg4thr1x** [comment]
Also, one last thing: since I keep changing my config.json continuosly (and I think it's the same for you), I decided to remove it from the repo, and just put it in my home folder. We can then upload a sample config.json at the end

**Comment by hcw1026** [comment]
I don't know much about the saving part. Except that, do you want to change the tensorboard parameter names so that it agrees with the current log-mel and waveform? It's up to you whether you want to restart your top15 tags training or restart it. If we all use the same names, then all the lines can appear on the same graph. Apart from that I'm happy with this PR

**Comment by pyg4thr1x** [comment]
@hcw1026, with Keras TensorBoard logs everything automatically, I didn't set the parameters names manually. I suggest it is easier to change the names on the custom script...

As for the logs that we already have, we'll keep them as they are. Or maybe we might be able to manually tweak the log files? 🤔

**Review by callesonne — APPROVED** [review]
I approve of this

**Pull request merged**
