### PR TITLE
Predict

### PR DESCRIPTION
**Pull request by callesonne**
test_model.py is a script for testing finished models as well as predicting tags of any user-provided mp3.
I have not played around with adens record.py yet, so I dont know if we want to keep this.

### CODE REVIEW

**Comment by callesonne** [comment]
Im currently working on documentating the branch

**Comment by hcw1026** [comment]
Comment:
**parse_config**: It's better if you import it from the training script, but then we might need to accept the merge_training PR...

**load_from_checkpoint**: Does it work for training.py?

**get_audio**: I have changed one line based on what Davide has changed in the input script, you may want to test it.

**test**: There's also a 'merge_tags' parameter you need to consider. 
And why multiply by 0.001?
Also I think for the AUC scores output, two decimal places is better.

**get_slices**: looks good

**predict**: looks good

**Comment by hcw1026** [comment]
I have integrated the record.py into the __main__ section. I have not tested it on this script yet since I don't have the model locally. If you have the model on your laptop, can you try to run it?

**Comment by pyg4thr1x** [comment]
Agree with Aden's comments... Just two remarks: 

> Does it work for training.py?

Since checkpoints are saved differently in the two scripts (blame the TensorFlow guys...) this will *always* be a problem. 

I propose two solutions: 
1. write duplicate functions for loading model (looks ugly), 
2. fuck model.fit and with the predict module you will only import custom checkpoints. Three points in favour of this: 
    1. the TF guys themselves say tf.train.Checkpoint is the preferred way to handle checkpoints...
    2. if we ever implements some more things like one cycle policy, chances are that it will be in the custom loops; 
    3. I'm encountering unexpected bugs with model.fit... Apparently when you run the training script _multiple times one after the other_, sometimes (but only sometimes!!!!) you get a dataset out of range error... I'm still investigating this, but it doesn't happen in custom loops

> It's better if you import it from the training script, but then we might need to accept the merge_training PR...

Yes, let's do this for now. At this point it might actually make more sense to separate parse_config in a different file, maybe projectname.py, and having the two training functions in the same file. But this are things for a different PR...

**Comment by hcw1026** [comment]
> Comment:
> parse_config: It's better if you import it from the training script, but then we might need to accept the merge_training PR...   CHANGED
> load_from_checkpoint: Does it work for training.py? NOT CHANGED
> get_audio: I have changed one line based on what Davide has changed in the input script, you may want to test it.
> test: There's also a 'merge_tags' parameter you need to consider. CHANGED
> And why multiply by 0.001? CHANGED
> Also I think for the AUC scores output, two decimal places is better. CHANGED
> get_slices: looks good
> predict: looks good

**Comment by hcw1026** [comment]
UPDATE:
1. I have removed the multiply by 0.001? Change it back if I'm wrong.
2. I have not changed how we restore checkpoint from projectname_train.py, you guys can do it....

**Comment by hcw1026** [comment]
Everything should work now except point 2 above.

**Review by pyg4thr1x — DISMISSED** [review]
Ok, here's the big changelog:
1. made the audio_slice function more functional (now it is indeed a sliding window, check it out)
2. changed the structure of argparse (make use of sub-commands, since test and predict are two quite different things which live in the same script)
3. added a simple progress bar to test (you might need to `pip install tqdm`)

The rest is all fuff

**Comment by pyg4thr1x** [comment]
> 1\. I have removed the multiply by 0.001? Change it back if I'm wrong.

No, that looks quite right to me...

> 2\. I have not changed how we restore checkpoint from projectname_train.py, you guys can do it...

I don't have any easy way to do it... I'm happy with things as they are

**Comment by pyg4thr1x** [comment]
All tested (apart from the `--record` part because of some missing library on my side, but I barely touched that part of the code, in Aden we trust)

**Review by pyg4thr1x — DISMISSED** [review]

**Comment by pyg4thr1x** [comment]
@callesonne?

**Pull request merged**
