### PR TITLE
Bug fix fix input.py

### PR DESCRIPTION
**Pull request by pyg4thr1x**
1) You can't use if/else statements when using tensors in graph mode, I substituted your if/else bug fix when using random window with a more concise tf.cond()

2) Substituted default cycle_length to 1 (doesn't matter, it's in the config anyways)

3) Fixed a bug when using generate_dataset with only one file (interleave doesn't work, found the bug on my laptop)

4) All the mess I had to do in the hotenc_mask function could have been achieved in a much more concise way with tf.gather(). The deprecation error also disappeared.

Side note: if you're merging this branch into aden_calle_model you might have some conflicts, since you guys edited input.py in that branch as well. If you merge, just accept _incoming changes_.

### CODE REVIEW

**Review by callesonne — COMMENTED** [review]
Great PR! I approve of everything. Could you explain to me why this line is necessary though:
`datasets = datasets + [None] * (which_split.count(1) - 1)`
To me it seems that if you dont specify a split you should just return one big dataset, the situation where you for some reason dont specify split but do specify which_split seems like it will never happen.

**Comment by pyg4thr1x** [comment]
> the situation where you for some reason dont specify split but do specify which_split seems like it will never happen.

It (used to) happen in my training script, when --split was a system argument, but which_split was hard coded as (True, True, False)... In that case, I didn't want an error when unpacking with train_dataset, valid_dataset =    but instead I wanted valid_dataset to be None

**Comment by pyg4thr1x** [comment]
@hcw1026 why didn't you like tf.gather and default cycle_length = 1?

**Comment by pyg4thr1x** [comment]
@hcw1026 why didn't you also like the possibility to treat split as percentage, and my bug fix with interleave (!!) ?

**Comment by pyg4thr1x** [comment]
I've fixed some bugs and used tf.cond instead of tf.where. All tested.

**Comment by callesonne** [comment]
god dammit I was working on that. You were faster than me though :)

**Comment by pyg4thr1x** [comment]
😉

**Comment by callesonne** [comment]
You can approve and merge if you want when you have tested it

**Comment by pyg4thr1x** [comment]
It's my pull request... I can't approve it 😅

**Comment by pyg4thr1x** [comment]
I have tested it already

**Review by callesonne — APPROVED** [review]
merging

**Pull request merged**
