### PR TITLE
Calle audio processing

### PR DESCRIPTION
**Pull request by callesonne**
This script does the following:
1. Reads tids and file paths from ultimate.csv
2. Reads the corresponding tags from clean_lastfm.db and converts to a one-hot vector.
3.  Opens the corresponding .npz file and converts it to mono and resamples.
3.5. IF SPECIFIED AS ARGUMENT will also convert to log-melspectrogram.
4. Saves tid+tags+waveform or spectrogram as features to a tfrecord file

It has multiple options for saving the tfrecord file:
- Saving num_files different tfrecord files of equal size
Or
- Saving 3 files, 1 train 1 test 1 validation and it is possible to specify the proportion.

- If the first option was chosen there is an argument that lets you specify which of the num_files files the instance should write, which is useful for splitting up the work in a tmux instance.

### CODE REVIEW

**Comment by callesonne** [comment]
Oh right... I will fix documentation soon, just prioritized getting the PR out ASAP so that I could fix the last parts of the parse PR

**Comment by pyg4thr1x** [comment]
I've tested it, I'm happy with it. As soon as Calle fixes the documentation, I'll approve

**Comment by hcw1026** [comment]
Comment:

**audio_format argument**
Will it be better if we default as none within the function?

**save_examples_to_tffile**
continue

**train/valid/test**
better doc, i.e. saying sum must be one

**__name__=='__main__'**:
train, val, test = [val/tot for val in values]   -- val is used twice but it shouldn't cause any problem I think. I comment it here just in case

I'll keep updating until I finish

**Comment by hcw1026** [comment]
DONE

**Comment by callesonne** [comment]
> Comment:
> 
> **audio_format argument**
> Will it be better if we default as none within the function?

Fixed
> **save_examples_to_tffile**
> continue

Fixed
> **train/valid/test**
> better doc, i.e. saying sum must be one

It doesnt need to be one, I ensure it to be one. You can do proportions as well 8/1/1 would work.
> ****name**=='**main**'**:
> train, val, test = [val/tot for val in values] -- val is used twice but it shouldn't cause any problem I think. I comment it here just in case

This does not matter, but maybe I should change the variable name to avoid confusion.

**Review by hcw1026 — APPROVED** [review]
The codes look great to me, although I am not able to test everything since I am getting a permission denied when saving tfrecord… I downloaded the scripts and run it under /home/aden/urop2019, why is that?

Anyway, I will approve it for now and you can merge it when you finish

**Comment by callesonne** [comment]
> The codes look great to me, although I am not able to test everything since I am getting a permission denied when saving tfrecord… I downloaded the scripts and run it under /home/aden/urop2019, why is that?

Thats very wierd, it should work... Only thing I could think of is that *technically* you wrote all the .npz files and maybe there is a limit on how much space you could use up? It would be stupid if that was the case though... Whats the exact error message?

**Comment by hcw1026** [comment]
> The codes look great to me, although I am not able to test everything since I am getting a permission denied when saving tfrecord… I downloaded the scripts and run it under /home/aden/urop2019, why is that?
> 
> Thats very wierd, it should work...

If it works for you then it's fine... maybe it's a boden problem

**Comment by callesonne** [comment]
Alright I will merge this and start creating the tfrecords

**Pull request merged**
