### PR TITLE
Quick PR: improve multi-database training

### PR DESCRIPTION
**Pull request by pyg4thr1x**
Changelog:
1) Use .get_shape() in input.py (sometimes some error appear when doing things locally that weren't there before...)
2) Fix 'unintended behaviour' when split array contains zeros in input.py
3) Add option to use different default databases for train and valid, when parsing TFRecs with more than one tags features
4) Add same options to training script

### CODE REVIEW

**Comment by hcw1026** [comment]
`Use get_shape. Improve split`:
datasets is a list, np.where(np.array([1,1,0])!=0, datasets, None] will return [datasets, datasets, 0], which datasets itself is also a list of datasets?

`Add support for different valid database`:
default_tags_db = default_tags_db_valid if default_tags_db is not None and default_tags_db_valid is not None else default_tags_db

After this line is defined, it is not used at all?
and the explanation of default_tags_db_valid is not clear

**Comment by pyg4thr1x** [comment]
> np.where(np.array([1,1,0])!=0, datasets, None] will return [datasets, datasets, 0], which datasets itself is also a list of datasets?

No, it will return [dataset_1, dataset_2, None], which is what you want

**Comment by pyg4thr1x** [comment]
> After this line is defined, it is not used at all?

So for example in my experiments with multiple datasets, you have 11 different tags databases in the TFRecords. You want to use n.5 for training (let's say), but n.0 for validation and testing (suppose n.0 is the standard one, not the experimental one). So you pass default_tags_db=0, default_tags_db_valid=5 and in the output `datasets` list, the first dataset (training) will parse the 5-th database, and the other ones (valid/test) will parse the 0-th one, which again is what you want

**Comment by pyg4thr1x** [comment]
> and the explanation of default_tags_db_valid is not clear

It's the index of the tags database that you want to use for valid/testing (when you have multiple db's in the tfrecs). How would you explain it?

**Comment by pyg4thr1x** [comment]
@hcw1026?

**Comment by hcw1026** [comment]
It's the index of the tags database that you want to use for valid/testing

This explanation is clearer than the inline doc

**Review by hcw1026 — DISMISSED** [review]

**Comment by pyg4thr1x** [comment]
I've changed the inline doc. @hcw1026, you can accept and merge

**Review by hcw1026 — APPROVED** [review]

**Pull request merged**
