### PR TITLE
One and Only One Training Script

### PR DESCRIPTION
**Pull request by pyg4thr1x**
Important files affected by this PR are training.py, training_custom.py, in minor part projectname.py (I added one new config parameter), and in extremely minor part preprocessing.py (I fixed one extremely minor issue with printing, too minor to be put in a stand-alone PR...)

Changelog:
1. Now the config parser makes use of the new config.json. 
I added min_learning rate to the config, for the reduce_lr on plateau callback.
I also set early_stop_patience and reduce_lr_patiance as *the only* parameters that determine whether early stop and reduce_lr are used, not all the others.
2. Logs and checkpoints are now saved in the same directory. (Why? Because I didin't understand why were separated in the first place, since I usually spend some good 5 minutes just trying to match checkpoints timestamps with logs timestamps 🤯)

The syntax of projectname_train.py is the same as the old training scripts. To select the custom one, just add a `--custom` option when calling the script. If nothing is specified, projectname_train.py goes for built-in

### CODE REVIEW

**Comment by hcw1026** [comment]
1. MyProgbar(), did you write it yourself?
2. Have you tested any of these?

**Comment by hcw1026** [comment]
finally, from my experience, os.environ['LD_LIBRARY_PATH'] = '/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/extras/CUPTI/lib64' won't work because the path is needed to be defined before python is initialised.

**Review by hcw1026 — DISMISSED** [review]
I have briefly tested the scripts and should work

**Review by hcw1026 — DISMISSED** [review]

**Comment by pyg4thr1x** [comment]
> 1. MyProgbar(), did you write it yourself?

No, that's tf.keras.utils.progbar. I apported some modification from the original source code, cause I was trying to make it work in graph mode, but I didn't succeed. MyProgbar needs not stay in utils, let's just import the TF one. 

There was a conflict with utils.py, couldn't merge. Approve and merge now

**Review by hcw1026 — APPROVED** [review]

**Pull request merged**
