### PR TITLE
lastfm on steroids

### PR DESCRIPTION
**Pull request by pyg4thr1x**
Check this out, should be extensively documented.

In particular, do 
`import lastfm`
`fm = lastfm.LastFm2Pandas(path_to_db)`
`matrix = lastfm.Matrix(fm, tags=[whatever], dim=3)`
`matrix.are_equivalent()`, 
or `matrix.all_tag_is()`,
or `matrix.all_tag_is_either()`

Apart from the usual (extremely minor) doc changes to a couple of other files, the only files affected by this PR are lastfm.py and utils.py

### CODE REVIEW

**Comment by hcw1026** [comment]
I really like the maths inside! nice work!
I'm still reading it but I'll keep commenting in case I forget.

**Comment by hcw1026** [comment]
what does et stands for... just curious
**tags_et**: 
idxs = np.where(np.array([self.m_tags] * len(tags)) == tags[:,None])[1]
assert len(idxs) == len(tags)
I don't understand this line. I thought this line assumes 'tags' is a list of string. But if this is so then what is tags[:,None]?

**Comment by hcw1026** [comment]
**correlation_matrix_3d(self)**, and **correlation_matrix_3d(self)**:
Will it be more efficient if you do:
for i in range(l): for j in range(i+1), for k in range(j+1), and then just set (i,k,j)=(i,j,k) etc.?

**Comment by hcw1026** [comment]
Everything looks great (especially the crazy sum!!). 
One more suggestion: it'd be better if there is a visualisation function with matplotlib (imshow will do the work). I can do the visualisation if you're too lazy to write one

**Comment by pyg4thr1x** [comment]
1. I've tested your plot function, and organized the code a bit differently.
2. Scipy.sparse only supports 2-D matrices, that's why I used sparse.

**Comment by pyg4thr1x** [comment]
> what does et stands for... just curious

3. it's Latin for 'and'. I've changed et into and

**Comment by pyg4thr1x** [comment]
> idxs = np.where(np.array([self.m_tags] * len(tags)) == tags[:,None])[1]

I just wanted to use numpy functions (they're faster?), but there's not such thing as ['rock', 'pop'].index('pop'), which returns the index of 'pop' in the list. That obscure line of code does the same thing, but does not return an error if 'pop' does not exist... It just returns an array of shorter length. Hence the assert

**Comment by pyg4thr1x** [comment]
> what is tags[:,None]

It changes the shape of the array. Try it out

**Comment by hcw1026** [comment]
I don't have time to change it, you can do the following if you wish.
Other suggestion:
1. add save option to the plot -- fig.save_fig() , possibly with higher dpi
2. variable figsize to the plot function, i.e. depends on the number of tags
3. fix the vec_tag_num_to_tag error, I would suggest not to have vec_tag_num_to_tag, but do a for loop within the function instead so that both classes have the same function names.
4. There are some docs in some of the functions of the two classes which aren't up-to-date, you may want to fix them. (actually I realised there are more in other scripts when I was writing the readme)
5. Alawys display progress, since it takes time even if I just want to generate a 2x2 matrix.

Other than test I am happy with this PR

**Comment by pyg4thr1x** [comment]
> 1\. add save option to the plot -- fig.save_fig() , possibly with higher dpi

Done. Highest DPI is default with plt.savefig. What do you want to do when producing multiple plots (in the 3D case)? Save them all? How about just saving in the single-plot case?

**Comment by pyg4thr1x** [comment]
> 2\. variable figsize to the plot function, i.e. depends on the number of tags

Done

**Comment by pyg4thr1x** [comment]
> 3\. fix the vec_tag_num_to_tag error, I would suggest not to have vec_tag_num_to_tag, but do a for loop within the function instead so that both classes have the same function names.

Done. Also fixed references in different files

**Comment by pyg4thr1x** [comment]
> 4\. There are some docs in some of the functions of the two classes which aren't up-to-date, you may want to fix them. (actually I realised there are more in other scripts when I was writing the readme)

???

**Comment by pyg4thr1x** [comment]
> 5\. Alawys display progress, since it takes time even if I just want to generate a 2x2 matrix.

Right now progress is displayed if more than 100 steps are needed. It takes less than 5 seconds to perform 100 steps, I would prefer not to have a prog bar in that case. Feel free to change that tho if you really want to always show it

**Comment by pyg4thr1x** [comment]
@hcw1026?

**Comment by hcw1026** [comment]
> 1. add save option to the plot -- fig.save_fig() , possibly with higher dpi
> 
> Done. Highest DPI is default with plt.savefig. What do you want to do when producing multiple plots (in the 3D case)? Save them all? How about just saving in the single-plot case?

sure

**Comment by hcw1026** [comment]
checkout the new bugfix, this fixes the vec_tag_num_to_tag bug we had before, and tag_num_to_tag in LastFm is consistent with that of LastFm2Pandas

**Review by hcw1026 — DISMISSED** [review]

**Comment by pyg4thr1x** [comment]
Ok, this might be a bit of an overkill, but np.vectorize is _much_ faster than a for loop when you need to do large scale stuff. Now LastFm2Pandas and LastFm give _exactly_ the same output. @hcw1026, check this out

**Review by hcw1026 — APPROVED** [review]

**Pull request merged**
