### PR TITLE
Calle davide create clean lastfm db

### PR DESCRIPTION
**Pull request by pyg4thr1x**
Here it is

### CODE REVIEW

**Comment by hcw1026** [comment]
Comments:
**flatten_to_tag_num() , and other functions as well:**
1) 'db' is repeated, i.e. db can mean import query_lastfm as db, or db=db.Lastfm 
2) in doc, column name should be merge_tags instead of merge-tags
3) the appended zero row is never used.

**create_tag_tag_table()**
1) It seems to me that the documentation is inconsistent with what is happening in the function. (since the row index produced by me has been changed in the final section of the script)
2) The 'index' column of flat is never used.
3) The tag series has no column name, but not consistent with the doc.


**In the __name__ = '__main__' part:**
1) ['merge_tag'] is not consistnet, should use ['merge_tags'] instead.
2) df['merge_tag'] = df['merge_tag'].map(ast.literal_eval) -- ast.literal_eval throws an error if the dataframe is imported directly from lastfm_tool.
3) df.index = df.index + 1   --- use df.copy() and then change index instead, or it will permanently changed to original df. So if you run it a few times, it will mess up the original df.

Done.

**Comment by hcw1026** [comment]
One more thing I didn't check:
In the dataframe I returned, all the tags are string. But some of the tags from the database are float, have you addressed that anywhere?

**Review by callesonne — COMMENTED** [review]
Why did you remove np.integer from isinstance checks?

**Comment by hcw1026** [comment]
**lastfm_clean review:**

**Start:**
1. import ast   --- ast is not used
2. import sqlite3 --- missing

**All the functions**
1. docstring not changed., e.g. db is still in the docstring

**if __name__ = '__main__':**
1. tags = df['tag'].srt.lower(), srt does not exist, should be str?



I will keep updating this comment until I finish

**Comment by pyg4thr1x** [comment]
I’ve fixed what you’ve written so far. Submit new comments in the case, so I’ll get notified

**Comment by hcw1026** [comment]
**lastfm_clean review:**

**All the functions**
1. docstring not changed., e.g. db is still in the docstring

**create_tag_tag**
1. BIG PROBLEM (tell me if I'm wrong)
The df from lastfm_tool is never re-indexed. That means the tag_num for flatten() starts with zero, and rock is mapped to 0. Then in create_tag_tag(), all the unused tags are mapped to zero. and finally rock is dropped in create_tid_tag_table(). You can check this by:
create+tag+tag+table(lastfm, df).loc[95] this will give zero

2. tag_tag.index +=1, why are you doing this? To me it seems like the **COLUMN** means the old ID, which I understand. But for the  **INDEX**, I think this also means old_ID, and then you will create a mapping between the **COLUMN** and tag_tag, so that the value of the COLUMN becomes the new_tag_num, i.e. create_tid_tag_table will create a series that maps old ID to new_tag_num, and finally this series will be used to map the 'tag' of the tidtag table into new_tag_num.

So I think it will make more sense if the **INDEX** of create_tag_tag_table is a duplicate of its **COLUMN**, which you used lf.get_tag_nums() to obtain that. Of course tag_tag.index +=1 will produce the same result, but it relies on the assumption that lf.get_tag_nums() = 1-500000+, and if we believe this assumption, then there is no point doing lf.get_tag_nums() at all.

Tell me if I interpreted tag_tag wrongly




I will keep updating this comment until I finish

**Comment by hcw1026** [comment]
Point 2 can be simplified if we just find out all the lastfm_IDs that are not in tag_num column of tag_tag, and produce a seperate series for these lastfm_IDs with zero column, and finally stack the two series vertically. But I don't mind either way as long as it works

**Comment by pyg4thr1x** [comment]
> **All the functions**
> 
> 1. docstring not changed., e.g. db is still in the docstring

db still in the docstring??? I might not have understood what you're referring to then... Please change it (in a single commit, so that I'll see where I missed them)

Found... (I think)

**Comment by pyg4thr1x** [comment]
> 1. BIG PROBLEM (tell me if I'm wrong)
>    The df from lastfm_tool is never re-indexed. That means the tag_num for flatten() starts with zero, and rock is mapped to 0. Then in create_tag_tag(), all the unused tags are mapped to zero. and finally rock is dropped in create_tid_tag_table(). You can check this by:
>    create+tag+tag+table(lastfm, df).loc[95] this will give zero

Fixed

**Comment by pyg4thr1x** [comment]
> 2\. tag_tag.index +=1, why are you doing this? To me it seems like the **COLUMN** means the old ID, which I understand. But for the  **INDEX**, I think this also means old_ID, and then you will create a mapping between the **COLUMN** and tag_tag, so that the value of the COLUMN becomes the new_tag_num, i.e. create_tid_tag_table will create a series that maps old ID to new_tag_num, and finally this series will be used to map the 'tag' of the tidtag table into new_tag_num.
> 
> So I think it will make more sense if the **INDEX** of create_tag_tag_table is a duplicate of its **COLUMN**, which you used lf.get_tag_nums() to obtain that. Of course tag_tag.index +=1 will produce the same result, but it relies on the assumption that lf.get_tag_nums() = 1-500000+, and if we believe this assumption, then there is no point doing lf.get_tag_nums() at all.

Fixed

**Comment by pyg4thr1x** [comment]
Seems all done to me. Check out the new files in /srv/data/urop. The two db files have been generated with these scripts. Check out also the new ultimate.csv. Apparently we've lost some 110K tracks with the clean database. Any other comments?

**Comment by hcw1026** [comment]
**Review of lastfm_clean: cont..**
**if __name__ == '__main__'**
1. if args.supp_txt_path:
        lf_tool.set_output_path(args.supp_txt_path)
It's no longer called set_output_path


I will keep updating this comment until I finish

**Comment by hcw1026** [comment]
Review for lastfm_clean done. I am happy with lastfm_clean now.

**Comment by hcw1026** [comment]
**Review for query_lastfm:**
**LastFm:**
Suggestions (optional):
1.  db_to_csv(), print progress
2.  db_to_csv(), set output_dir to be os.path.dirname(self.path) (and add self.path=path to __init__)

**Review by callesonne — DISMISSED** [review]
I am happy with this, just a few questions on code I dont understand:

LastFm2Pandas.popularity:
- Why is this line necessary?
`self.pop = pd.concat([self.pop['tag'], self.pop['tag_num'], self.pop['count']], axis=1)`

lastfm_clean:
- Why do you want the NaNs that the following line gives you for tids with no new_tid_nums?
`    tids = tids.map(lastfm.tid_num_to_tid).reindex(pd.RangeIndex(1, len(lastfm.get_tid_nums())+1))`

**Comment by hcw1026** [comment]
**Review query_lastfm (LastFm2Pandas)**
Changes made in last commit:
1) add order option to preserve order of input arrays to some LastFm2Pandas funcs
2) fixed a bug in tid_num_to_tag_nums
3) add order to doc
4) added .values to  tag_to_tag_num to .index.values, so it returns array instead of index.

some doc may still be inconsistent (I haven't changed):
tid_to_tid_num: return str?

**Suggestion (optional)** (I haven't changed):
1) return list instead of array for str output?

**Comment by hcw1026** [comment]
> Review for query_lastfm:
> LastFm:
> Suggestions (optional):
> 
> db_to_csv(), print progress
> db_to_csv(), set output_dir to be os.path.dirname(self.path) (and add self.path=path to init)

Implemented the suggestions

Changes on db_to_csv():
1. default output_dir
2. print progress
3. add doc for output_dir

feel free to delete any if you disagree

**Review by hcw1026 — APPROVED** [review]
I am happy with this pull request after the remaining bits are sorted.

**Comment by callesonne** [comment]
Im also happy with everything except the order option in LastFm2Pandas, I dont get it. If someone can explain it to me I will merge the PR:
Running:
print(lf.tid_to_tid_num(lf.tid_num_to_tid([1,2,3,4,5])))
print(lf.tid_to_tid_num(lf.tid_num_to_tid([5,4,3,2,1], order=True), order=True))
Gives:
> [1,2,3,4,5]
> [1,2,3,4,5]

So does order do anything, or am I missing its purpose?

**Comment by callesonne** [comment]
I though I tested all cases, turns out I missed the one where order=False screws up. Im approving

**Pull request merged**
