### PR TITLE
Query MSD Summary

### PR DESCRIPTION
**Pull request by pyg4thr1x**
This is the very first script I have been working on, and I should have probably pulled it earlier... It makes use of the msd_summary_file.h5 and track_metadata.db files to get title, artist_id, year (or whatever) for a list of tracks.

We will probably never use it in production, but it might still be useful for experimentation, or for someone "exploring" our repository.

I think it is worth pulling it to master, but I am happy to keep it in the "recycle bin" branch if you guys think that's more appropriate...

Feedback?

### CODE REVIEW

**Comment by pyg4thr1x** [comment]
SIDE NOTE: Calle's module on this branch has been renamed to query_lastfm.py (because in this way we would have two files that both start with the word 'query', which is nice 😇🤗)

**Comment by callesonne** [comment]
I am just wondering, what is your motivation for doing (in query_lastfm.py): 
`output = res.fetchone(), output = output[0]` Instead of `output = res.fetchone()[0]`

**Comment by callesonne** [comment]
Review:
Firstly, very nicely structured script! I found it very easy to read despite not being that familiar with your work. Now I think it looks good but there are some changes I would suggest. All of these changes are fairly unimportant and can be skipped if you wish but I think they would improve the module:
1. In general I think you need to document exactly what types of input to the parameter *ids your function will support. The reason for this is that it supports a lot of different types so it is not clear what will work and will not work, e.g. mixing integers and strings seems to not work and by looking at the code I dont think giving multiple lists will work either.
2. (again you can ignore this if you like just to be clear) In get_attribute() you store the two types in id_type then index it to say what type you are you are using. I dont really see the point of this and feel like it would be more readable if you did: 
`id_type = ""`
`if ...:`
    `...`
    `    id_type = "track_id"`
`elif ...:`
    `...`
    `    id_type = "track_id"`
`elif ...:`
    `...`
    `    id_type = "song_id"`
Again, this is up to you.

**Comment by pyg4thr1x** [comment]
> I am just wondering, what is your motivation for doing (in query_lastfm.py):
> `output = res.fetchone(), output = output[0]` Instead of `output = res.fetchone()[0]`

None, really...

**Review by callesonne — COMMENTED** [review]
I am not sure but I think you might need a id_type = "" at the beginning of the if statements, otherwise it will only exist within the if scope.

**Comment by pyg4thr1x** [comment]
Haven't tested it yet... I'll try the script in a second

**Comment by pyg4thr1x** [comment]
By the way, I haven't replied here, but I am planning to fix your point 1 as well. I don't think multiple arguments are needed. I can accept either a list (of id's of the same type) or a single ID, and that's it. Nobody is ever going to use multiple arguments

**Comment by callesonne** [comment]
Great!

> I don't think multiple arguments are needed. I can accept either a list (of id's of the same type) or a single ID, and that's it. Nobody is ever going to use multiple arguments

Ah okay then can I suggest the following change to get_trackid_from_7digitalid:
`if all([isinstance(id, int) for id in ids]):`
                `ids = [str(id) for id in ids]`
to:
`if not all([isinstance(id, str) for id in ids]):`
`ids = [str(id) for id in ids]`
This will let you mix strings + ids in the list. Although I am not sure in what scenario one would want to do that, so this may actually not be needed. It doesnt add any code though

**Comment by callesonne** [comment]
Or maybe even just:
`ids = [str(id) for id in ids]`

**Comment by pyg4thr1x** [comment]
> I am not sure but I think you might need a id_type = "" at the beginning of the if statements, otherwise it will only exist within the if scope.

@callesonne, it works. Apparently there's no such thing as an if scope, a variable defined within an if statement still has function scope.

**Comment by callesonne** [comment]
> > I am not sure but I think you might need a id_type = "" at the beginning of the if statements, otherwise it will only exist within the if scope.
> 
> @callesonne, it works. Apparently there's no such thing as an if scope, a variable defined within an if statement still has function scope.

Great! one less line.

**Review by callesonne — DISMISSED** [review]
I approve of this now. @hcw1026 and @anaghmalik do you guys want to have a look as well?

**Comment by pyg4thr1x** [comment]
I am trying to write a good documentation for the get_attribute function (add a couple of example). Give me 5-10 mins and I'll be done

**Comment by pyg4thr1x** [comment]
Done.

Thanks @callesonne for the feedback. @hcw1026, @anaghmalik let me know if it's good for you.

**Comment by hcw1026** [comment]
I have no comment on that. I have read it some time last week I think👍👍

**Review by callesonne — APPROVED** [review]
Lets merge then? I (once again) approve of the changes.

**Comment by callesonne** [comment]
No last minute changes @pyg4thr1x ?

**Comment by pyg4thr1x** [comment]
> No last minute changes @pyg4thr1x ?

Let's merge it now, otherwise I might come up with some 😝

**Pull request merged**
